// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/fdddf/opentrans/internal/database"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAppLocalization(db *gorm.DB, opts ...gen.DOOption) appLocalization {
	_appLocalization := appLocalization{}

	_appLocalization.appLocalizationDo.UseDB(db, opts...)
	_appLocalization.appLocalizationDo.UseModel(&database.AppLocalization{})

	tableName := _appLocalization.appLocalizationDo.TableName()
	_appLocalization.ALL = field.NewAsterisk(tableName)
	_appLocalization.ID = field.NewUint(tableName, "id")
	_appLocalization.CreatedAt = field.NewTime(tableName, "created_at")
	_appLocalization.UpdatedAt = field.NewTime(tableName, "updated_at")
	_appLocalization.DeletedAt = field.NewField(tableName, "deleted_at")
	_appLocalization.AppID = field.NewUint(tableName, "app_id")
	_appLocalization.LanguageCode = field.NewString(tableName, "language_code")
	_appLocalization.Name = field.NewString(tableName, "name")
	_appLocalization.Subtitle = field.NewString(tableName, "subtitle")
	_appLocalization.PrivacyURL = field.NewString(tableName, "privacy_url")
	_appLocalization.MarketingURL = field.NewString(tableName, "marketing_url")
	_appLocalization.SupportURL = field.NewString(tableName, "support_url")
	_appLocalization.Description = field.NewString(tableName, "description")
	_appLocalization.Keywords = field.NewString(tableName, "keywords")
	_appLocalization.WhatsNew = field.NewString(tableName, "whats_new")
	_appLocalization.PromotionalText = field.NewString(tableName, "promotional_text")
	_appLocalization.WhatToTest = field.NewString(tableName, "what_to_test")
	_appLocalization.SyncedAt = field.NewTime(tableName, "synced_at")
	_appLocalization.Source = field.NewString(tableName, "source")
	_appLocalization.SyncStatus = field.NewString(tableName, "sync_status")
	_appLocalization.Version = field.NewString(tableName, "version")
	_appLocalization.VersionState = field.NewString(tableName, "version_state")
	_appLocalization.Locale = field.NewString(tableName, "locale")
	_appLocalization.App = appLocalizationBelongsToApp{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("App", "database.App"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("App.User", "database.User"),
		},
	}

	_appLocalization.fillFieldMap()

	return _appLocalization
}

type appLocalization struct {
	appLocalizationDo

	ALL                 field.Asterisk
	ID                  field.Uint
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	AppID               field.Uint
	LanguageCode        field.String
	Name                field.String
	Subtitle            field.String
	PrivacyURL          field.String
	MarketingURL        field.String
	SupportURL          field.String
	Description         field.String
	Keywords            field.String
	WhatsNew            field.String
	PromotionalText     field.String
	WhatToTest          field.String
	SyncedAt            field.Time
	Source              field.String
	SyncStatus          field.String
	Version             field.String
	VersionState        field.String
	Locale              field.String
	App                 appLocalizationBelongsToApp

	fieldMap map[string]field.Expr
}

func (a appLocalization) Table(newTableName string) *appLocalization {
	a.appLocalizationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appLocalization) As(alias string) *appLocalization {
	a.appLocalizationDo.DO = *(a.appLocalizationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appLocalization) updateTableName(table string) *appLocalization {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.AppID = field.NewUint(table, "app_id")
	a.LanguageCode = field.NewString(table, "language_code")
	a.Name = field.NewString(table, "name")
	a.Subtitle = field.NewString(table, "subtitle")
	a.PrivacyURL = field.NewString(table, "privacy_url")
	a.MarketingURL = field.NewString(table, "marketing_url")
	a.SupportURL = field.NewString(table, "support_url")
	a.Description = field.NewString(table, "description")
	a.Keywords = field.NewString(table, "keywords")
	a.WhatsNew = field.NewString(table, "whats_new")
	a.PromotionalText = field.NewString(table, "promotional_text")
	a.WhatToTest = field.NewString(table, "what_to_test")
	a.SyncedAt = field.NewTime(table, "synced_at")
	a.Source = field.NewString(table, "source")
	a.SyncStatus = field.NewString(table, "sync_status")
	a.Version = field.NewString(table, "version")
	a.VersionState = field.NewString(table, "version_state")
	a.Locale = field.NewString(table, "locale")

	a.fillFieldMap()

	return a
}

func (a *appLocalization) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appLocalization) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 23)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["language_code"] = a.LanguageCode
	a.fieldMap["name"] = a.Name
	a.fieldMap["subtitle"] = a.Subtitle
	a.fieldMap["privacy_url"] = a.PrivacyURL
	a.fieldMap["marketing_url"] = a.MarketingURL
	a.fieldMap["support_url"] = a.SupportURL
	a.fieldMap["description"] = a.Description
	a.fieldMap["keywords"] = a.Keywords
	a.fieldMap["whats_new"] = a.WhatsNew
	a.fieldMap["promotional_text"] = a.PromotionalText
	a.fieldMap["what_to_test"] = a.WhatToTest
	a.fieldMap["synced_at"] = a.SyncedAt
	a.fieldMap["source"] = a.Source
	a.fieldMap["sync_status"] = a.SyncStatus
	a.fieldMap["version"] = a.Version
	a.fieldMap["version_state"] = a.VersionState
	a.fieldMap["locale"] = a.Locale

}

func (a appLocalization) clone(db *gorm.DB) appLocalization {
	a.appLocalizationDo.ReplaceConnPool(db.Statement.ConnPool)
	a.App.db = db.Session(&gorm.Session{Initialized: true})
	a.App.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a appLocalization) replaceDB(db *gorm.DB) appLocalization {
	a.appLocalizationDo.ReplaceDB(db)
	a.App.db = db.Session(&gorm.Session{})
	return a
}

type appLocalizationBelongsToApp struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
}

func (a appLocalizationBelongsToApp) Where(conds ...field.Expr) *appLocalizationBelongsToApp {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a appLocalizationBelongsToApp) WithContext(ctx context.Context) *appLocalizationBelongsToApp {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a appLocalizationBelongsToApp) Session(session *gorm.Session) *appLocalizationBelongsToApp {
	a.db = a.db.Session(session)
	return &a
}

func (a appLocalizationBelongsToApp) Model(m *database.AppLocalization) *appLocalizationBelongsToAppTx {
	return &appLocalizationBelongsToAppTx{a.db.Model(m).Association(a.Name())}
}

func (a appLocalizationBelongsToApp) Unscoped() *appLocalizationBelongsToApp {
	a.db = a.db.Unscoped()
	return &a
}

type appLocalizationBelongsToAppTx struct{ tx *gorm.Association }

func (a appLocalizationBelongsToAppTx) Find() (result *database.App, err error) {
	return result, a.tx.Find(&result)
}

func (a appLocalizationBelongsToAppTx) Append(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a appLocalizationBelongsToAppTx) Replace(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a appLocalizationBelongsToAppTx) Delete(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a appLocalizationBelongsToAppTx) Clear() error {
	return a.tx.Clear()
}

func (a appLocalizationBelongsToAppTx) Count() int64 {
	return a.tx.Count()
}

func (a appLocalizationBelongsToAppTx) Unscoped() *appLocalizationBelongsToAppTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type appLocalizationDo struct{ gen.DO }

type IAppLocalizationDo interface {
	gen.SubQuery
	Debug() IAppLocalizationDo
	WithContext(ctx context.Context) IAppLocalizationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppLocalizationDo
	WriteDB() IAppLocalizationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppLocalizationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppLocalizationDo
	Not(conds ...gen.Condition) IAppLocalizationDo
	Or(conds ...gen.Condition) IAppLocalizationDo
	Select(conds ...field.Expr) IAppLocalizationDo
	Where(conds ...gen.Condition) IAppLocalizationDo
	Order(conds ...field.Expr) IAppLocalizationDo
	Distinct(cols ...field.Expr) IAppLocalizationDo
	Omit(cols ...field.Expr) IAppLocalizationDo
	Join(table schema.Tabler, on ...field.Expr) IAppLocalizationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppLocalizationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppLocalizationDo
	Group(cols ...field.Expr) IAppLocalizationDo
	Having(conds ...gen.Condition) IAppLocalizationDo
	Limit(limit int) IAppLocalizationDo
	Offset(offset int) IAppLocalizationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppLocalizationDo
	Unscoped() IAppLocalizationDo
	Create(values ...*database.AppLocalization) error
	CreateInBatches(values []*database.AppLocalization, batchSize int) error
	Save(values ...*database.AppLocalization) error
	First() (*database.AppLocalization, error)
	Take() (*database.AppLocalization, error)
	Last() (*database.AppLocalization, error)
	Find() ([]*database.AppLocalization, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.AppLocalization, err error)
	FindInBatches(result *[]*database.AppLocalization, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*database.AppLocalization) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppLocalizationDo
	Assign(attrs ...field.AssignExpr) IAppLocalizationDo
	Joins(fields ...field.RelationField) IAppLocalizationDo
	Preload(fields ...field.RelationField) IAppLocalizationDo
	FirstOrInit() (*database.AppLocalization, error)
	FirstOrCreate() (*database.AppLocalization, error)
	FindByPage(offset int, limit int) (result []*database.AppLocalization, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppLocalizationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appLocalizationDo) Debug() IAppLocalizationDo {
	return a.withDO(a.DO.Debug())
}

func (a appLocalizationDo) WithContext(ctx context.Context) IAppLocalizationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appLocalizationDo) ReadDB() IAppLocalizationDo {
	return a.Clauses(dbresolver.Read)
}

func (a appLocalizationDo) WriteDB() IAppLocalizationDo {
	return a.Clauses(dbresolver.Write)
}

func (a appLocalizationDo) Session(config *gorm.Session) IAppLocalizationDo {
	return a.withDO(a.DO.Session(config))
}

func (a appLocalizationDo) Clauses(conds ...clause.Expression) IAppLocalizationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appLocalizationDo) Returning(value interface{}, columns ...string) IAppLocalizationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appLocalizationDo) Not(conds ...gen.Condition) IAppLocalizationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appLocalizationDo) Or(conds ...gen.Condition) IAppLocalizationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appLocalizationDo) Select(conds ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appLocalizationDo) Where(conds ...gen.Condition) IAppLocalizationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appLocalizationDo) Order(conds ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appLocalizationDo) Distinct(cols ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appLocalizationDo) Omit(cols ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appLocalizationDo) Join(table schema.Tabler, on ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appLocalizationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appLocalizationDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appLocalizationDo) Group(cols ...field.Expr) IAppLocalizationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appLocalizationDo) Having(conds ...gen.Condition) IAppLocalizationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appLocalizationDo) Limit(limit int) IAppLocalizationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appLocalizationDo) Offset(offset int) IAppLocalizationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appLocalizationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppLocalizationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appLocalizationDo) Unscoped() IAppLocalizationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appLocalizationDo) Create(values ...*database.AppLocalization) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appLocalizationDo) CreateInBatches(values []*database.AppLocalization, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appLocalizationDo) Save(values ...*database.AppLocalization) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appLocalizationDo) First() (*database.AppLocalization, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppLocalization), nil
	}
}

func (a appLocalizationDo) Take() (*database.AppLocalization, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppLocalization), nil
	}
}

func (a appLocalizationDo) Last() (*database.AppLocalization, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppLocalization), nil
	}
}

func (a appLocalizationDo) Find() ([]*database.AppLocalization, error) {
	result, err := a.DO.Find()
	return result.([]*database.AppLocalization), err
}

func (a appLocalizationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.AppLocalization, err error) {
	buf := make([]*database.AppLocalization, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appLocalizationDo) FindInBatches(result *[]*database.AppLocalization, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appLocalizationDo) Attrs(attrs ...field.AssignExpr) IAppLocalizationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appLocalizationDo) Assign(attrs ...field.AssignExpr) IAppLocalizationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appLocalizationDo) Joins(fields ...field.RelationField) IAppLocalizationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appLocalizationDo) Preload(fields ...field.RelationField) IAppLocalizationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appLocalizationDo) FirstOrInit() (*database.AppLocalization, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppLocalization), nil
	}
}

func (a appLocalizationDo) FirstOrCreate() (*database.AppLocalization, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppLocalization), nil
	}
}

func (a appLocalizationDo) FindByPage(offset int, limit int) (result []*database.AppLocalization, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appLocalizationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appLocalizationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appLocalizationDo) Delete(models ...*database.AppLocalization) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appLocalizationDo) withDO(do gen.Dao) *appLocalizationDo {
	a.DO = *do.(*gen.DO)
	return a
}
